---
- name: Copy env configuration file ( Debian )
  template:
    src: activemq-env.j2
    dest: /etc/default/activemq-instance-{{ amq_broker_instance_name }}
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'
  notify:
    - restart activemq

- name: Copy env configuration file ( CentOS & RH )
  template:
    src: activemq-env-rh.j2
    dest: /etc/sysconfig/{{ amq_broker_instance_name }}
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'
  notify:
    - restart activemq

- name: Copy groups and users properties templates
  template:
    src: "{{ item }}.j2"
    dest: '{{ amq_conf_dir }}/{{ item }}'
    owner: '{{ amq_user }}'
    group: '{{ amq_group }}'
    mode: 0644
  when:
    - amq_custom_xml_config == False
  with_items:
    - groups.properties
    - users.properties


- name: Copy activemq.xml config file
  template:
    src: activemq.xml.j2
    dest: '{{ amq_conf_dir }}/activemq.xml'
    owner: '{{ amq_user }}'
    group: '{{ amq_group }}'
    mode: 0644
  when:
    - amq_custom_xml_config == False

- name: Copy custom activemq.xml config file
  template:
    src: '{{ amq_custom_xml_config_path }}'
    dest: '{{ amq_conf_dir }}/activemq.xml'
    owner: '{{ amq_user }}'
    group: '{{ amq_group }}'
    mode: 0644
  when:
    - amq_custom_xml_config == True

- name: Set webconsole port
  replace:
    dest: '{{ amq_conf_dir }}/jetty.xml'
    regexp: '<property name="port" value="\d+"'
    replace: '<property name="port" value="{{ amq_webconsole_port }}"'
  notify:
    - restart activemq

- name: Change path to store log file
  lineinfile:
    dest: '{{ amq_conf_dir }}/log4j.properties'
    regexp: '^log4j.appender.logfile.file='
    line: 'log4j.appender.logfile.file=/var/log/{{ amq_broker_instance_name }}/activemq.log'
    state: present
  notify:
    - restart activemq

- name: Init script ( Debian )
  file:
    src: '{{ amq_install_dir }}/bin/activemq'
    dest: '/etc/init.d/activemq-instance-{{ amq_broker_instance_name }}'
    state: link
  when: ansible_os_family == 'Debian'

- name: Init script ( Debian )
  template:
    src: activemq-init.j2
    dest: /etc/init.d/{{ amq_broker_instance_name }}
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == 'RedHat'
  notify:
    - restart activemq
  tags:
    - init
 
