---
- name: Pre-install tasks
  import_tasks: prepare.yml
  tags:
    - preinstall

- name: Install tasks
  import_tasks: install.yml
  tags:
    - install

- name: Config tasks
  import_tasks: config.yml
  tags:
    - config

- name: Post-install tasks
  import_tasks: afterinstall.yml
  tags:
    - postinstall
